### ISSUE TITLE
Színek

### ISSUE THREAD

**Issue by pbnjit** [sandorbence05/projektmunka_911#9]
Olvashatatlan a szöveg ezen a háttérszínen. Próbáljatok valami más háttérszínt vagy betűszínt választani, vagy képet beilleszteni helyette. A sötétkéken minden esetben olvashatatlan lesz a fekete.
![kép](https://user-images.githubusercontent.com/90724183/136154112-71f4b73a-f68c-4320-903c-fef120590da8.png)

**Comment by sandorbence05** [comment]
Megvan
